
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

desc "Bump build number based on most recent TestFlight build number"
lane :fetch_and_increment_build_number do

 current_version = get_version_number(
   target: "MoSoContent"
 )
 latest_build_number = latest_testflight_build_number(
   version: current_version,
   app_identifier: "com.ReadItLater.Ebony"
 )
 increment_build_number(
   build_number: (latest_build_number + 1),
   skip_info_plist: true
 )
end

lane :build_debug do
  update_code_signing_settings(
      use_automatic_signing: false,
      path: "MoSoContent.xcodeproj",
      code_sign_identity: "iPhone Development",
      sdk: "iphoneos*",
      profile_name: "EbonyDevelopmentProfile",
    )
    build_app(
      scheme: "MoSoContent",
      export_method: "development",
      configuration: "Debug",
      export_options: {
        provisioningProfiles: {
          "com.ReadItLater.Ebony" => "EbonyDevelopmentProfile"
        }
      }
    )
end

lane :build_beta do
  update_code_signing_settings(
      use_automatic_signing: false,
      path: "MoSoContent.xcodeproj",
      code_sign_identity: "iPhone Distribution",
      sdk: "iphoneos*",
      profile_name: "EbonyDistributionProfile",
    )
    build_app(
      scheme: "MoSoContent",
      export_method: "app-store",
      configuration: "Release",
      export_options: {
        provisioningProfiles: {
          "com.ReadItLater.Ebony" => "EbonyDistributionProfile"
        }
      }
    )
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    fetch_and_increment_build_number
    build_beta
    upload_to_testflight
  end
end
